// Generated by gir (https://github.com/gtk-rs/gir @ 81e2ef9e1ab7)
// from ../../gir-files (@ 3b6fe0a33676)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_16);
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_22);
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_24);
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_32);
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_48);
    PRINT_CONSTANT((gint) XAPP_ICON_SIZE_96);
    PRINT_CONSTANT((gint) XAPP_SCROLL_DOWN);
    PRINT_CONSTANT((gint) XAPP_SCROLL_LEFT);
    PRINT_CONSTANT((gint) XAPP_SCROLL_RIGHT);
    PRINT_CONSTANT((gint) XAPP_SCROLL_UP);
    PRINT_CONSTANT((gint) XAPP_STATUS_ICON_STATE_FALLBACK);
    PRINT_CONSTANT((gint) XAPP_STATUS_ICON_STATE_NATIVE);
    PRINT_CONSTANT((gint) XAPP_STATUS_ICON_STATE_NO_SUPPORT);
    return 0;
}
