// Generated by gir (https://github.com/gtk-rs/gir @ b5068ede6c51)
// from ../../gir-files (@ 248ad6976459)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XAppFavoriteInfo", sizeof(XAppFavoriteInfo), alignof(XAppFavoriteInfo));
    printf("%s;%zu;%zu\n", "XAppFavoritesClass", sizeof(XAppFavoritesClass), alignof(XAppFavoritesClass));
    printf("%s;%zu;%zu\n", "XAppGtkWindow", sizeof(XAppGtkWindow), alignof(XAppGtkWindow));
    printf("%s;%zu;%zu\n", "XAppGtkWindowClass", sizeof(XAppGtkWindowClass), alignof(XAppGtkWindowClass));
    printf("%s;%zu;%zu\n", "XAppIconChooserButtonClass", sizeof(XAppIconChooserButtonClass), alignof(XAppIconChooserButtonClass));
    printf("%s;%zu;%zu\n", "XAppIconChooserDialogClass", sizeof(XAppIconChooserDialogClass), alignof(XAppIconChooserDialogClass));
    printf("%s;%zu;%zu\n", "XAppIconSize", sizeof(XAppIconSize), alignof(XAppIconSize));
    printf("%s;%zu;%zu\n", "XAppKbdLayoutController", sizeof(XAppKbdLayoutController), alignof(XAppKbdLayoutController));
    printf("%s;%zu;%zu\n", "XAppKbdLayoutControllerClass", sizeof(XAppKbdLayoutControllerClass), alignof(XAppKbdLayoutControllerClass));
    printf("%s;%zu;%zu\n", "XAppMonitorBlankerClass", sizeof(XAppMonitorBlankerClass), alignof(XAppMonitorBlankerClass));
    printf("%s;%zu;%zu\n", "XAppObjectIface", sizeof(XAppObjectIface), alignof(XAppObjectIface));
    printf("%s;%zu;%zu\n", "XAppObjectManagerClient", sizeof(XAppObjectManagerClient), alignof(XAppObjectManagerClient));
    printf("%s;%zu;%zu\n", "XAppObjectManagerClientClass", sizeof(XAppObjectManagerClientClass), alignof(XAppObjectManagerClientClass));
    printf("%s;%zu;%zu\n", "XAppObjectProxy", sizeof(XAppObjectProxy), alignof(XAppObjectProxy));
    printf("%s;%zu;%zu\n", "XAppObjectProxyClass", sizeof(XAppObjectProxyClass), alignof(XAppObjectProxyClass));
    printf("%s;%zu;%zu\n", "XAppObjectSkeleton", sizeof(XAppObjectSkeleton), alignof(XAppObjectSkeleton));
    printf("%s;%zu;%zu\n", "XAppObjectSkeletonClass", sizeof(XAppObjectSkeletonClass), alignof(XAppObjectSkeletonClass));
    printf("%s;%zu;%zu\n", "XAppPreferencesWindow", sizeof(XAppPreferencesWindow), alignof(XAppPreferencesWindow));
    printf("%s;%zu;%zu\n", "XAppPreferencesWindowClass", sizeof(XAppPreferencesWindowClass), alignof(XAppPreferencesWindowClass));
    printf("%s;%zu;%zu\n", "XAppScrollDirection", sizeof(XAppScrollDirection), alignof(XAppScrollDirection));
    printf("%s;%zu;%zu\n", "XAppStackSidebarClass", sizeof(XAppStackSidebarClass), alignof(XAppStackSidebarClass));
    printf("%s;%zu;%zu\n", "XAppStatusIconClass", sizeof(XAppStatusIconClass), alignof(XAppStatusIconClass));
    printf("%s;%zu;%zu\n", "XAppStatusIconInterfaceIface", sizeof(XAppStatusIconInterfaceIface), alignof(XAppStatusIconInterfaceIface));
    printf("%s;%zu;%zu\n", "XAppStatusIconInterfaceProxy", sizeof(XAppStatusIconInterfaceProxy), alignof(XAppStatusIconInterfaceProxy));
    printf("%s;%zu;%zu\n", "XAppStatusIconInterfaceProxyClass", sizeof(XAppStatusIconInterfaceProxyClass), alignof(XAppStatusIconInterfaceProxyClass));
    printf("%s;%zu;%zu\n", "XAppStatusIconInterfaceSkeleton", sizeof(XAppStatusIconInterfaceSkeleton), alignof(XAppStatusIconInterfaceSkeleton));
    printf("%s;%zu;%zu\n", "XAppStatusIconInterfaceSkeletonClass", sizeof(XAppStatusIconInterfaceSkeletonClass), alignof(XAppStatusIconInterfaceSkeletonClass));
    printf("%s;%zu;%zu\n", "XAppStatusIconMonitorClass", sizeof(XAppStatusIconMonitorClass), alignof(XAppStatusIconMonitorClass));
    printf("%s;%zu;%zu\n", "XAppStatusIconState", sizeof(XAppStatusIconState), alignof(XAppStatusIconState));
    printf("%s;%zu;%zu\n", "XAppStyleManagerClass", sizeof(XAppStyleManagerClass), alignof(XAppStyleManagerClass));
    return 0;
}
