// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

mod favorites;
pub use self::favorites::Favorites;

mod gtk_window;
pub use self::gtk_window::GtkWindow;

mod icon_chooser_button;
pub use self::icon_chooser_button::IconChooserButton;

mod icon_chooser_dialog;
pub use self::icon_chooser_dialog::IconChooserDialog;

mod kbd_layout_controller;
pub use self::kbd_layout_controller::KbdLayoutController;

mod monitor_blanker;
pub use self::monitor_blanker::MonitorBlanker;

mod object;
pub use self::object::Object;

mod object_manager_client;
pub use self::object_manager_client::ObjectManagerClient;

mod object_proxy;
pub use self::object_proxy::ObjectProxy;

mod object_skeleton;
pub use self::object_skeleton::ObjectSkeleton;

mod preferences_window;
pub use self::preferences_window::PreferencesWindow;

mod stack_sidebar;
pub use self::stack_sidebar::StackSidebar;

mod status_icon;
pub use self::status_icon::StatusIcon;

mod status_icon_interface;
pub use self::status_icon_interface::StatusIconInterface;

mod status_icon_interface_proxy;
pub use self::status_icon_interface_proxy::StatusIconInterfaceProxy;

mod status_icon_interface_skeleton;
pub use self::status_icon_interface_skeleton::StatusIconInterfaceSkeleton;

mod status_icon_monitor;
pub use self::status_icon_monitor::StatusIconMonitor;

mod style_manager;
pub use self::style_manager::StyleManager;

mod favorite_info;
pub use self::favorite_info::FavoriteInfo;

mod enums;
pub use self::enums::IconSize;
pub use self::enums::ScrollDirection;
pub use self::enums::StatusIconState;

#[doc(hidden)]
pub mod traits {
    pub use super::gtk_window::GtkWindowExt;
    pub use super::kbd_layout_controller::KbdLayoutControllerExt;
    pub use super::object::ObjectExt;
    pub use super::object_skeleton::ObjectSkeletonExt;
    pub use super::preferences_window::PreferencesWindowExt;
    pub use super::status_icon_interface::StatusIconInterfaceExt;
}
#[doc(hidden)]
pub mod builders {
    pub use super::gtk_window::GtkWindowBuilder;
    pub use super::icon_chooser_button::IconChooserButtonBuilder;
    pub use super::icon_chooser_dialog::IconChooserDialogBuilder;
    pub use super::object_manager_client::ObjectManagerClientBuilder;
    pub use super::object_proxy::ObjectProxyBuilder;
    pub use super::object_skeleton::ObjectSkeletonBuilder;
    pub use super::preferences_window::PreferencesWindowBuilder;
    pub use super::stack_sidebar::StackSidebarBuilder;
    pub use super::status_icon::StatusIconBuilder;
    pub use super::status_icon_interface_proxy::StatusIconInterfaceProxyBuilder;
    pub use super::status_icon_interface_skeleton::StatusIconInterfaceSkeletonBuilder;
    pub use super::style_manager::StyleManagerBuilder;
}
