// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::Object;
use crate::StatusIconInterface;
use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use glib::StaticType;
use glib::ToValue;
use std::fmt;

#[cfg(any(feature = "gio_v2_30", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "gio_v2_30")))]
glib::wrapper! {
    #[doc(alias = "XAppObjectSkeleton")]
    pub struct ObjectSkeleton(Object<ffi::XAppObjectSkeleton, ffi::XAppObjectSkeletonClass>) @extends gio::DBusObjectSkeleton, @implements gio::DBusObject, Object;

    match fn {
        type_ => || ffi::xapp_object_skeleton_get_type(),
    }
}

#[cfg(not(any(feature = "gio_v2_30", feature = "dox")))]
glib::wrapper! {
    #[doc(alias = "XAppObjectSkeleton")]
    pub struct ObjectSkeleton(Object<ffi::XAppObjectSkeleton, ffi::XAppObjectSkeletonClass>) @implements gio::DBusObject, Object;

    match fn {
        type_ => || ffi::xapp_object_skeleton_get_type(),
    }
}

impl ObjectSkeleton {
        pub const NONE: Option<&'static ObjectSkeleton> = None;
    

    #[doc(alias = "xapp_object_skeleton_new")]
    pub fn new(object_path: &str) -> ObjectSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::xapp_object_skeleton_new(object_path.to_glib_none().0))
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`ObjectSkeleton`] objects.
            ///
            /// This method returns an instance of [`ObjectSkeletonBuilder`](crate::builders::ObjectSkeletonBuilder) which can be used to create [`ObjectSkeleton`] objects.
            pub fn builder() -> ObjectSkeletonBuilder {
                ObjectSkeletonBuilder::default()
            }
        
}

impl Default for ObjectSkeleton {
                     fn default() -> Self {
                         glib::object::Object::new::<Self>(&[])
                     }
                 }

#[derive(Clone, Default)]
// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`ObjectSkeleton`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct ObjectSkeletonBuilder {
    #[cfg(any(feature = "gio_v2_30", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gio_v2_30")))]
    g_object_path: Option<String>,
    status_icon_interface: Option<StatusIconInterface>,
}

impl ObjectSkeletonBuilder {
    // rustdoc-stripper-ignore-next
    /// Create a new [`ObjectSkeletonBuilder`].
    pub fn new() -> Self {
        Self::default()
    }


    // rustdoc-stripper-ignore-next
    /// Build the [`ObjectSkeleton`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> ObjectSkeleton {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
        #[cfg(any(feature = "gio_v2_30", feature = "dox"))]
if let Some(ref g_object_path) = self.g_object_path {
                properties.push(("g-object-path", g_object_path));
            }
if let Some(ref status_icon_interface) = self.status_icon_interface {
                properties.push(("status-icon-interface", status_icon_interface));
            }
        glib::Object::new::<ObjectSkeleton>(&properties)

    }

    #[cfg(any(feature = "gio_v2_30", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gio_v2_30")))]
    pub fn g_object_path(mut self, g_object_path: &str) -> Self {
        self.g_object_path = Some(g_object_path.to_string());
        self
    }

    pub fn status_icon_interface(mut self, status_icon_interface: &impl IsA<StatusIconInterface>) -> Self {
        self.status_icon_interface = Some(status_icon_interface.clone().upcast());
        self
    }
}

pub trait ObjectSkeletonExt: 'static {
    #[doc(alias = "xapp_object_skeleton_set_status_icon_interface")]
    fn set_status_icon_interface(&self, interface_: Option<&impl IsA<StatusIconInterface>>);
}

impl<O: IsA<ObjectSkeleton>> ObjectSkeletonExt for O {
    fn set_status_icon_interface(&self, interface_: Option<&impl IsA<StatusIconInterface>>) {
        unsafe {
            ffi::xapp_object_skeleton_set_status_icon_interface(self.as_ref().to_glib_none().0, interface_.map(|p| p.as_ref()).to_glib_none().0);
        }
    }
}

impl fmt::Display for ObjectSkeleton {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ObjectSkeleton")
    }
}
